
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 14;
  public static final int MENOR = 9;
  public static final int ELSE = 21;
  public static final int INT = 18;
  public static final int OR = 13;
  public static final int IGUAL = 11;
  public static final int WHILE = 22;
  public static final int DIVISION = 8;
  public static final int SUMA = 5;
  public static final int IF = 20;
  public static final int ID = 27;
  public static final int CADENATEXTO = 26;
  public static final int LLAVEIZQ = 16;
  public static final int ASIGNAR = 15;
  public static final int LLAVEDER = 17;
  public static final int DISTINTO = 12;
  public static final int MAYOR = 10;
  public static final int EOF = 0;
  public static final int MAIN = 19;
  public static final int BREAK = 25;
  public static final int PUTW = 24;
  public static final int error = 1;
  public static final int PUTS = 23;
  public static final int PARENDER = 3;
  public static final int PUNTOCOMA = 4;
  public static final int PRODUCTO = 7;
  public static final int ENTERO = 28;
  public static final int PARENTIZQ = 2;
  public static final int RESTA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTIZQ",
  "PARENDER",
  "PUNTOCOMA",
  "SUMA",
  "RESTA",
  "PRODUCTO",
  "DIVISION",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "DISTINTO",
  "OR",
  "AND",
  "ASIGNAR",
  "LLAVEIZQ",
  "LLAVEDER",
  "INT",
  "MAIN",
  "IF",
  "ELSE",
  "WHILE",
  "PUTS",
  "PUTW",
  "BREAK",
  "CADENATEXTO",
  "ID",
  "ENTERO"
  };
}

